//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assistant_settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub version_id: i32,
    pub system_prompt: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::prompt_settings::Entity",
        from = "Column::VersionId",
        to = "super::prompt_settings::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PromptSettings,
}

impl Related<super::prompt_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PromptSettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
