//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chat_settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub version_id: i32,
    pub system_prompt: String,
    pub response_format: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::setting_versions::Entity",
        from = "Column::VersionId",
        to = "super::setting_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SettingVersions,
}

impl Related<super::setting_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SettingVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
