//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "comparing_prompt_runs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub manager_id: i32,
    pub provider_type: Option<String>,
    pub model: String,
    pub user_prompt: String,
    #[sea_orm(column_type = "Double")]
    pub temperature: f64,
    pub max_token: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::comparing_prompt_manager::Entity",
        from = "Column::ManagerId",
        to = "super::comparing_prompt_manager::Column::ManagerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ComparingPromptManager,
    #[sea_orm(has_many = "super::comparing_prompt_run_histories::Entity")]
    ComparingPromptRunHistories,
}

impl Related<super::comparing_prompt_manager::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptManager.def()
    }
}

impl Related<super::comparing_prompt_run_histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptRunHistories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
