//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comparing_prompt_run_histories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub run_id: i32,
    pub version_id: i32,
    pub response: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::comparing_prompt_runs::Entity",
        from = "Column::RunId",
        to = "super::comparing_prompt_runs::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ComparingPromptRuns,
    #[sea_orm(
        belongs_to = "super::comparing_prompt_setting_versions::Entity",
        from = "Column::VersionId",
        to = "super::comparing_prompt_setting_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ComparingPromptSettingVersions,
}

impl Related<super::comparing_prompt_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptRuns.def()
    }
}

impl Related<super::comparing_prompt_setting_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptSettingVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
