//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comparing_prompt_manager")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub manager_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comparing_prompt_runs::Entity")]
    ComparingPromptRuns,
    #[sea_orm(has_many = "super::comparing_prompt_settings::Entity")]
    ComparingPromptSettings,
    #[sea_orm(
        belongs_to = "super::prompt_manager::Entity",
        from = "Column::ManagerId",
        to = "super::prompt_manager::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PromptManager,
}

impl Related<super::comparing_prompt_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptRuns.def()
    }
}

impl Related<super::comparing_prompt_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptSettings.def()
    }
}

impl Related<super::prompt_manager::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PromptManager.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
