//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comparing_prompt_settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub manager_id: i32,
    pub current_version: i32,
    pub deleted_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::comparing_prompt_manager::Entity",
        from = "Column::ManagerId",
        to = "super::comparing_prompt_manager::Column::ManagerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ComparingPromptManager,
    #[sea_orm(has_many = "super::comparing_prompt_setting_versions::Entity")]
    ComparingPromptSettingVersions,
}

impl Related<super::comparing_prompt_manager::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptManager.def()
    }
}

impl Related<super::comparing_prompt_setting_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptSettingVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
