//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comparing_prompt_setting_versions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub version: i32,
    pub setting_id: i32,
    pub system_prompt: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comparing_prompt_chat_setting_details::Entity")]
    ComparingPromptChatSettingDetails,
    #[sea_orm(has_many = "super::comparing_prompt_run_histories::Entity")]
    ComparingPromptRunHistories,
    #[sea_orm(
        belongs_to = "super::comparing_prompt_settings::Entity",
        from = "Column::SettingId",
        to = "super::comparing_prompt_settings::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ComparingPromptSettings,
    #[sea_orm(has_many = "super::comparing_prompt_vision_setting_details::Entity")]
    ComparingPromptVisionSettingDetails,
}

impl Related<super::comparing_prompt_chat_setting_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptChatSettingDetails.def()
    }
}

impl Related<super::comparing_prompt_run_histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptRunHistories.def()
    }
}

impl Related<super::comparing_prompt_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptSettings.def()
    }
}

impl Related<super::comparing_prompt_vision_setting_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptVisionSettingDetails.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
