//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod assistant_settings;
pub mod chat_settings;
pub mod prompt_manger;
pub mod prompt_manger_versions;
pub mod run_histories;
pub mod runs;
