//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod assistant_settings;
pub mod chat_settings;
pub mod prompt_manager;
pub mod prompt_manager_tag;
pub mod prompt_setting_versions;
pub mod prompt_settings;
pub mod run_histories;
pub mod runs;
pub mod tag;
