//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::assistant_settings::Entity as AssistantSettings;
pub use super::chat_settings::Entity as ChatSettings;
pub use super::run_histories::Entity as RunHistories;
pub use super::runs::Entity as Runs;
pub use super::setting_versions::Entity as SettingVersions;
pub use super::settings::Entity as Settings;
