//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "prompt_manager")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub api_type: Option<String>,
    pub deleted_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::prompt_manager_tag::Entity")]
    PromptManagerTag,
    #[sea_orm(has_many = "super::prompt_settings::Entity")]
    PromptSettings,
    #[sea_orm(has_many = "super::runs::Entity")]
    Runs,
}

impl Related<super::prompt_manager_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PromptManagerTag.def()
    }
}

impl Related<super::prompt_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PromptSettings.def()
    }
}

impl Related<super::runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Runs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

// impl Related<super::prompt_manager::Entity>
//     for crate::infra::repository::entities::prompt_manager::Entity
// {
//     fn to() -> RelationDef {
//         super::prompt_manager_tag::Relation::PromptManager.def()
//     }
//
//     fn via() -> Option<RelationDef> {
//         Some(super::prompt_manager_tag::Relation::Tag.def().rev())
//     }
// }

// impl Related<super::tag::Entity> for Entity {
//     fn to() -> RelationDef {
//         super::prompt_manager_tag::Relation::Tag.def()
//     }
//
//     fn via() -> Option<RelationDef> {
//         Some(
//             super::prompt_manager_tag::Relation::PromptManager
//                 .def()
//                 .rev(),
//         )
//     }
// }
