//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "prompt_manager")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub action_type: Option<String>,
    pub api_type: Option<String>,
    pub deleted_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comparing_prompt_manager::Entity")]
    ComparingPromptManager,
    #[sea_orm(has_many = "super::prompt_manager_tag::Entity")]
    PromptManagerTag,
}

impl Related<super::comparing_prompt_manager::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComparingPromptManager.def()
    }
}

impl Related<super::prompt_manager_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PromptManagerTag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
