//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "prompt_manager_tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub prompt_manager_id: i32,
    pub tag_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::prompt_manager::Entity",
        from = "Column::PromptManagerId",
        to = "super::prompt_manager::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PromptManager,
    #[sea_orm(
        belongs_to = "super::tag::Entity",
        from = "Column::TagId",
        to = "super::tag::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tag,
}

impl Related<super::prompt_manager::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PromptManager.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
