//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "run_histories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub run_id: i32,
    pub version_id: i32,
    pub response: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::prompt_manger_versions::Entity",
        from = "Column::VersionId",
        to = "super::prompt_manger_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PromptMangerVersions,
    #[sea_orm(
        belongs_to = "super::runs::Entity",
        from = "Column::RunId",
        to = "super::runs::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Runs,
}

impl Related<super::prompt_manger_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PromptMangerVersions.def()
    }
}

impl Related<super::runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Runs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
