//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "runs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub setting_id: i32,
    pub user_prompt: String,
    pub model: String,
    #[sea_orm(column_type = "Double")]
    pub temperature: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::run_histories::Entity")]
    RunHistories,
    #[sea_orm(
        belongs_to = "super::settings::Entity",
        from = "Column::SettingId",
        to = "super::settings::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Settings,
}

impl Related<super::run_histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RunHistories.def()
    }
}

impl Related<super::settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Settings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
