//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "runs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub manager_id: i32,
    pub user_prompt: String,
    pub model: String,
    #[sea_orm(column_type = "Double")]
    pub temperature: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::prompt_manager::Entity",
        from = "Column::ManagerId",
        to = "super::prompt_manager::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PromptManager,
    #[sea_orm(has_many = "super::run_histories::Entity")]
    RunHistories,
}

impl Related<super::prompt_manager::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PromptManager.def()
    }
}

impl Related<super::run_histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RunHistories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
